const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
require('dotenv').config();

const User = require('../models/User');
const Product = require('../models/Product');
const { Category, Brand, Banner, Coupon } = require('../models/index');

const seedData = async () => {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('Connected to MongoDB');

  // Clear existing data
  await Promise.all([
    User.deleteMany(),
    Product.deleteMany(),
    Category.deleteMany(),
    Brand.deleteMany(),
    Banner.deleteMany(),
    Coupon.deleteMany(),
  ]);
  console.log('Cleared existing data');

  // Create Super Admin
  const superAdmin = await User.create({
    name: 'Super Admin',
    email: 'admin@thankless.com'
    password: 'admin123456',
    role: 'superadmin',
    isVerified: true,
  });
  console.log('Super Admin created: admin@thankless.com / admin123456');

  // Create test customer
  await User.create({
    name: 'Test Customer',
    email: 'customer@thankless.com'
    password: 'customer123',
    role: 'customer',
    isVerified: true,
    phone: '9876543210',
  });
  console.log('Test Customer: customer@overrated.com / customer123');

  // Create Categories
  const categories = await Category.insertMany([
    { name: 'T-Shirts', slug: 't-shirts', gender: 'men', isActive: true, order: 1 },
    { name: 'Shirts', slug: 'shirts', gender: 'men', isActive: true, order: 2 },
    { name: 'Jeans', slug: 'jeans', gender: 'men', isActive: true, order: 3 },
    { name: 'Dresses', slug: 'dresses', gender: 'women', isActive: true, order: 4 },
    { name: 'Tops', slug: 'tops', gender: 'women', isActive: true, order: 5 },
    { name: 'Sarees', slug: 'sarees', gender: 'women', isActive: true, order: 6 },
    { name: 'Kurtis', slug: 'kurtis', gender: 'women', isActive: true, order: 7 },
    { name: 'Kids Wear', slug: 'kids-wear', gender: 'kids', isActive: true, order: 8 },
    { name: 'Shoes', slug: 'shoes', gender: 'unisex', isActive: true, order: 9 },
    { name: 'Accessories', slug: 'accessories', gender: 'unisex', isActive: true, order: 10 },
  ]);
  console.log(`${categories.length} categories created`);

  // Create Brands
  const brands = await Brand.insertMany([
    { name: 'Overrated Original', slug: 'overrated-original', isActive: true, isFeatured: true },
    { name: 'Fabindia', slug: 'fabindia', isActive: true, isFeatured: true },
    { name: 'Manyavar', slug: 'manyavar', isActive: true, isFeatured: true },
    { name: 'W for Woman', slug: 'w-for-woman', isActive: true },
    { name: 'Biba', slug: 'biba', isActive: true },
    { name: 'Allen Solly', slug: 'allen-solly', isActive: true },
    { name: 'Boyanika', slug: 'boyanika', isActive: true, isFeatured: true },
    { name: 'Utkalika', slug: 'utkalika', isActive: true, isFeatured: true },
  ]);
  console.log(`${brands.length} brands created`);

  // Placeholder image for all products
  const img = (q) => `https://images.unsplash.com/photo-${q}?w=600&h=800&fit=crop`;

  // Create Products
  const products = await Product.insertMany([
    {
      name: 'Classic White Cotton T-Shirt',
      slug: 'classic-white-cotton-t-shirt',
      description: 'Premium 100% cotton t-shirt with a comfortable regular fit. Perfect for everyday wear.',
      shortDescription: 'Premium 100% cotton, regular fit',
      price: 799,
      comparePrice: 1299,
      discount: 38,
      category: categories[0]._id,
      brand: brands[0]._id,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'White', hex: '#ffffff' }, { name: 'Black', hex: '#000000' }, { name: 'Navy', hex: '#001f5b' }],
      stock: 150,
      images: [{ url: img('1521572163474-6864f9cf17ab'), isMain: true }, { url: img('1503341504253-dff4815485f1'), isMain: false }],
      ratings: 4.5,
      numReviews: 128,
      tags: ['cotton', 'casual', 'basics'],
      isNewArrival: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      name: 'Elegant Silk Saree - Royal Blue',
      slug: 'elegant-silk-saree-royal-blue',
      description: 'Handwoven pure silk saree with intricate golden zari work. A timeless piece for festive occasions.',
      shortDescription: 'Pure silk, handwoven with golden zari',
      price: 4999,
      comparePrice: 7999,
      discount: 37,
      category: categories[5]._id,
      brand: brands[1]._id,
      sizes: ['Free Size'],
      colors: [{ name: 'Royal Blue', hex: '#4169e1' }, { name: 'Deep Red', hex: '#8b0000' }],
      stock: 45,
      images: [{ url: img('1610030469983-98e550d6193c'), isMain: true }, { url: img('1609357605129-26f69add5d6e'), isMain: false }],
      ratings: 4.8,
      numReviews: 256,
      tags: ['silk', 'saree', 'festive', 'traditional'],
      isNewArrival: true,
      isFeatured: true,
      isActive: true,
    },
    {
      name: 'Slim Fit Stretch Jeans',
      slug: 'slim-fit-stretch-jeans',
      description: 'Modern slim fit jeans made from premium stretch denim for maximum comfort and style.',
      shortDescription: 'Premium stretch denim, slim fit',
      price: 1599,
      comparePrice: 2499,
      discount: 36,
      category: categories[2]._id,
      brand: brands[5]._id,
      sizes: ['28', '30', '32', '34', '36', '38'],
      colors: [{ name: 'Dark Blue', hex: '#00008b' }, { name: 'Black', hex: '#000000' }, { name: 'Light Blue', hex: '#add8e6' }],
      stock: 200,
      images: [{ url: img('1542272604-787c3835535d'), isMain: true }],
      ratings: 4.3,
      numReviews: 89,
      tags: ['jeans', 'denim', 'casual'],
      isBestSeller: true,
      isActive: true,
    },
    {
      name: 'Floral Printed Kurti',
      slug: 'floral-printed-kurti',
      description: 'Beautiful floral printed kurti in soft cotton fabric. Perfect for both casual and semi-formal occasions.',
      shortDescription: 'Soft cotton, floral print',
      price: 899,
      comparePrice: 1499,
      discount: 40,
      category: categories[6]._id,
      brand: brands[3]._id,
      sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'Pink', hex: '#ffc0cb' }, { name: 'Blue', hex: '#0000ff' }, { name: 'Yellow', hex: '#ffff00' }],
      stock: 120,
      images: [{ url: img('1608748010899-18f300247112'), isMain: true }],
      ratings: 4.6,
      numReviews: 203,
      tags: ['kurti', 'cotton', 'floral', 'women'],
      isNewArrival: true,
      isBestSeller: true,
      isFlashSale: true,
      flashSalePrice: 699,
      flashSaleEnd: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      isActive: true,
    },
    {
      name: 'Men\'s Formal Oxford Shirt',
      slug: 'mens-formal-oxford-shirt',
      description: 'Classic Oxford weave formal shirt. Perfect for office wear and formal occasions.',
      shortDescription: 'Oxford weave, slim fit',
      price: 1299,
      comparePrice: 1999,
      discount: 35,
      category: categories[1]._id,
      brand: brands[5]._id,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'White', hex: '#ffffff' }, { name: 'Blue', hex: '#0000ff' }, { name: 'Grey', hex: '#808080' }],
      stock: 80,
      images: [{ url: img('1503341504253-dff4815485f1'), isMain: true }],
      ratings: 4.4,
      numReviews: 67,
      tags: ['formal', 'shirt', 'office'],
      isFeatured: true,
      isActive: true,
    },
    {
      name: 'Bohemian Wrap Dress',
      slug: 'bohemian-wrap-dress',
      description: 'Elegant wrap dress with bohemian prints. Flattering silhouette for all body types.',
      shortDescription: 'Wrap style, bohemian print',
      price: 1999,
      comparePrice: 3499,
      discount: 43,
      category: categories[3]._id,
      brand: brands[3]._id,
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      colors: [{ name: 'Multicolor', hex: '#ff69b4' }, { name: 'Teal', hex: '#008080' }],
      stock: 60,
      images: [{ url: img('1595777457583-95e059d581b8'), isMain: true }],
      ratings: 4.7,
      numReviews: 145,
      tags: ['dress', 'bohemian', 'casual', 'summer'],
      isNewArrival: true,
      isFlashSale: true,
      flashSalePrice: 1499,
      flashSaleEnd: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
      isActive: true,
    },
    {
      name: 'Traditional Phulkari Dupatta',
      slug: 'traditional-phulkari-dupatta',
      description: 'Authentic hand-embroidered Phulkari dupatta from Punjab. A cultural treasure.',
      shortDescription: 'Hand-embroidered Phulkari work',
      price: 1499,
      comparePrice: 2499,
      discount: 40,
      category: categories[9]._id,
      brand: brands[1]._id,
      sizes: ['Free Size'],
      colors: [{ name: 'Red', hex: '#ff0000' }, { name: 'Orange', hex: '#ffa500' }, { name: 'Pink', hex: '#ffc0cb' }],
      stock: 35,
      images: [{ url: img('1605721911519-3dfeb3be25e7'), isMain: true }],
      ratings: 4.9,
      numReviews: 178,
      tags: ['dupatta', 'phulkari', 'traditional', 'handmade'],
      isFeatured: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      name: 'Kids Cotton Ethnic Set',
      slug: 'kids-cotton-ethnic-set',
      description: 'Comfortable cotton ethnic set for kids. Perfect for festivals and family occasions.',
      shortDescription: 'Soft cotton, ethnic design',
      price: 699,
      comparePrice: 1199,
      discount: 42,
      category: categories[7]._id,
      brand: brands[0]._id,
      sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y'],
      colors: [{ name: 'Yellow', hex: '#ffff00' }, { name: 'Green', hex: '#008000' }, { name: 'Orange', hex: '#ffa500' }],
      stock: 90,
      images: [{ url: img('1519457431-44ccd64a579b'), isMain: true }],
      ratings: 4.5,
      numReviews: 92,
      tags: ['kids', 'ethnic', 'cotton', 'festival'],
      isNewArrival: true,
      isActive: true,
    },
    {
      name: 'Premium Sambalpuri Silk Saree - Pasaapali Design',
      slug: 'premium-sambalpuri-silk-saree-pasaapali-design',
      description: 'An exquisite, authentic Sambalpuri Silk Saree showcasing the traditional Pasaapali (chessboard) pattern. Handwoven with extreme care by master weavers of Bargarh, Odisha, utilizing tie-and-dye (Ikat) silk yarn. Certified with Silk Mark for 100% pure mulberry silk.',
      shortDescription: '100% pure silk, handwoven Pasaapali design',
      price: 8499,
      comparePrice: 12999,
      discount: 34,
      category: categories[5]._id,
      brand: brands[6]._id,
      sizes: ['Free Size'],
      colors: [{ name: 'Black & Red', hex: '#800000' }, { name: 'Gold & Black', hex: '#ffd700' }],
      stock: 12,
      images: [{ url: img('1610030469983-98e550d6193c'), isMain: true }, { url: img('1609357605129-26f69add5d6e'), isMain: false }],
      ratings: 4.9,
      numReviews: 48,
      tags: ['handloom', 'sambalpuri', 'silk', 'saree', 'ikat'],
      isNewArrival: true,
      isFeatured: true,
      isActive: true,
    },
    {
      name: 'Khandua Patta Silk Saree - Lord Jagannath Traditional',
      slug: 'khandua-patta-silk-saree-lord-jagannath-traditional',
      description: 'A holy Khandua Patta Saree from Nuapatna, Odisha, traditionally offered to Lord Jagannath. Features handwoven calligraphic shlokas and intricate borders representing rich Odia heritage. Pure mulberry silk weave with high-lustre finish.',
      shortDescription: 'Auspicious Nuapatna silk, temple borders',
      price: 9499,
      comparePrice: 14999,
      discount: 36,
      category: categories[5]._id,
      brand: brands[7]._id,
      sizes: ['Free Size'],
      colors: [{ name: 'Crimson Red', hex: '#990000' }, { name: 'Mustard Yellow', hex: '#ffdb58' }],
      stock: 8,
      images: [{ url: img('1610030469983-98e550d6193c'), isMain: true }],
      ratings: 4.8,
      numReviews: 32,
      tags: ['handloom', 'khandua', 'patta', 'silk', 'traditional'],
      isFeatured: true,
      isActive: true,
    },
    {
      name: 'Men\'s Sambalpuri Ikat Cotton Kurta',
      slug: 'mens-sambalpuri-ikat-cotton-kurta',
      description: 'Exquisite men\'s long kurta crafted in authentic handwoven Sambalpuri cotton. Features a vertical ikat weave, elegant mandarin collar, button placket, and side pockets. Highly breathable and perfect for formal, casual, or festive occasions.',
      shortDescription: '100% handloom cotton, vertical ikat weave',
      price: 1599,
      comparePrice: 2499,
      discount: 36,
      category: categories[1]._id,
      brand: brands[6]._id,
      sizes: ['M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'Teal Blue', hex: '#008080' }, { name: 'Rust Red', hex: '#b22222' }],
      stock: 65,
      images: [{ url: img('1618220179428-22790b461013'), isMain: true }],
      ratings: 4.6,
      numReviews: 54,
      tags: ['kurta', 'sambalpuri', 'cotton', 'men', 'handloom'],
      isNewArrival: true,
      isBestSeller: true,
      isActive: true,
    },
    {
      name: 'Women\'s Sambalpuri Cotton Kurti',
      slug: 'womens-sambalpuri-cotton-kurti',
      description: 'A stylish and comfortable straight-fit kurti made of handloom Sambalpuri cotton. Styled with standard three-quarter sleeves and a notch neckline. Featuring traditional Odisha ikat geometric motifs.',
      shortDescription: 'Sambalpuri handloom cotton kurti',
      price: 1299,
      comparePrice: 1999,
      discount: 35,
      category: categories[6]._id,
      brand: brands[6]._id,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'Olive Green', hex: '#556b2f' }, { name: 'Charcoal Black', hex: '#333333' }],
      stock: 80,
      images: [{ url: img('1608748010899-18f300247112'), isMain: true }],
      ratings: 4.7,
      numReviews: 76,
      tags: ['kurti', 'cotton', 'women', 'ikat', 'handloom'],
      isBestSeller: true,
      isActive: true,
    },
    {
      name: 'Pipli Applique Handwoven Canvas Tote',
      slug: 'pipli-applique-handwoven-canvas-tote',
      description: 'Spacious and durable tote bag detailed with traditional applique patchwork from Pipli, Odisha. Stitched with beautiful animal and tree-of-life embroidery motifs. Includes internal zipper compartments and sturdy leather-like handles.',
      shortDescription: 'Pipli applique embroidery, heavy-duty canvas',
      price: 799,
      comparePrice: 1299,
      discount: 38,
      category: categories[9]._id,
      brand: brands[7]._id,
      sizes: ['Free Size'],
      colors: [{ name: 'Beige & Red', hex: '#f5f5dc' }, { name: 'Black & Gold', hex: '#1a1a1a' }],
      stock: 40,
      images: [{ url: img('1535632066927-ab7c9ab60908'), isMain: true }],
      ratings: 4.5,
      numReviews: 29,
      tags: ['bag', 'applique', 'pipli', 'canvas', 'handmade'],
      isFlashSale: true,
      flashSalePrice: 599,
      flashSaleEnd: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
      isActive: true,
    },
    {
      name: 'Kotpad Natural Dye Organic Saree',
      slug: 'kotpad-natural-dye-organic-saree',
      description: 'An eco-friendly, organic cotton Kotpad Saree. Dyed entirely with natural ingredients, primarily the roots of the Indian Madder (Aal) tree. Featuring a rich earthy brown tone and traditional tribal border designs woven by tribal artisans.',
      shortDescription: 'Earthy Kotpad cotton, 100% natural organic dyes',
      price: 6999,
      comparePrice: 9999,
      discount: 30,
      category: categories[5]._id,
      brand: brands[6]._id,
      sizes: ['Free Size'],
      colors: [{ name: 'Earthy Brown', hex: '#654321' }, { name: 'Deep Red-Brown', hex: '#800020' }],
      stock: 5,
      images: [{ url: img('1609357605129-26f69add5d6e'), isMain: true }],
      ratings: 4.8,
      numReviews: 18,
      tags: ['kotpad', 'cotton', 'natural-dye', 'saree', 'organic'],
      isNewArrival: true,
      isActive: true,
    },
    {
      name: 'Men\'s Sambalpuri Ikat Casual Shirt',
      slug: 'mens-sambalpuri-ikat-casual-shirt',
      description: 'Elevate your casual wardrobe with this half-sleeved shirt made from handwoven Sambalpuri cotton. Displays fine, minimalist grey and white ikat checks. Styled with a classic collar and wooden buttons.',
      shortDescription: 'Handloom cotton, half sleeves, wooden buttons',
      price: 1399,
      comparePrice: 1999,
      discount: 30,
      category: categories[1]._id,
      brand: brands[6]._id,
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: [{ name: 'Slate Grey', hex: '#708090' }, { name: 'Ocean Blue', hex: '#4682b4' }],
      stock: 45,
      images: [{ url: img('1507679799987-c73779587ccf'), isMain: true }],
      ratings: 4.4,
      numReviews: 43,
      tags: ['shirt', 'sambalpuri', 'casual', 'men', 'ikat'],
      isBestSeller: true,
      isActive: true,
    },
  ]);
  console.log(`${products.length} products created`);

  // Create Banners
  await Banner.insertMany([
    {
      title: 'New Season Arrivals',
      subtitle: "Shop Men's Collection",
      description: 'Discover the latest trends in men\'s fashion',
      image: { url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600&h=900&fit=crop' },
      link: '/products?gender=men',
      buttonText: 'Shop Now',
      position: 'hero',
      order: 1,
      isActive: true,
    },
    {
      title: 'Elegance Redefined',
      subtitle: "Women's Festive Collection",
      description: 'Luxury sarees and ethnic wear for every occasion',
      image: { url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=1600&h=900&fit=crop' },
      link: '/products?gender=women',
      buttonText: "Explore Women's",
      position: 'hero',
      order: 2,
      isActive: true,
    },
    {
      title: '⚡ Flash Sale Up to 50% Off',
      subtitle: 'Limited Time Offer',
      description: 'Don\'t miss out on these exclusive deals',
      image: { url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1600&h=900&fit=crop' },
      link: '/products?isFlashSale=true',
      buttonText: 'Shop Sale',
      position: 'hero',
      order: 3,
      isActive: true,
    },
  ]);
  console.log('Banners created');

  // Create Coupons
  await Coupon.insertMany([
    {
      code: 'FIRST10',
      type: 'percentage',
      value: 10,
      minOrderAmount: 499,
      maxDiscount: 200,
      usageLimit: 1000,
      endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      description: '10% off on your first order',
      isFirstOrder: true,
      isActive: true,
    },
    {
      code: 'SAVE200',
      type: 'flat',
      value: 200,
      minOrderAmount: 999,
      usageLimit: 500,
      endDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
      description: '₹200 flat discount on orders above ₹999',
      isActive: true,
    },
    {
      code: 'FESTIVAL25',
      type: 'percentage',
      value: 25,
      minOrderAmount: 1999,
      maxDiscount: 500,
      usageLimit: 200,
      endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
      description: 'Festival special — 25% off',
      isActive: true,
    },
    {
      code: 'WELCOME50',
      type: 'flat',
      value: 50,
      minOrderAmount: 299,
      usageLimit: 2000,
      endDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      description: '₹50 welcome discount',
      isActive: true,
    },
  ]);
  console.log('Coupons created');

  console.log('\n✅ Database seeded successfully!');
  console.log('─────────────────────────────────');
  console.log('🔑 Admin Login: admin@overrated.com / admin123456');
  console.log('👤 Test User:   customer@overrated.com / customer123');
  console.log('🎟  Coupons:    FIRST10, SAVE200, FESTIVAL25, WELCOME50');
  console.log('─────────────────────────────────');
  process.exit(0);
};

seedData().catch(err => { console.error('Seeding failed:', err); process.exit(1); });
